python = "~3.11"
matplotlib = "^3.6.1"
numpy = "^1.23.3"
pre-commit = "^2.20.0"
pdbpp = "^0.10.3"
tqdm = "^4.64.1"
pydot = "^1.4.2"
tk = "^0.1.0"
drake = "^1.24"
pytest = "^7.4.0"
ffmpeg = "^1.4"
ffmpeg-python = "^0.2.0"
pygame = "^2.5.1"
manipulation = {git = "https://github.com/RussTedrake/manipulation.git"}
pyrealsense2 = "^2.54.2.5684"
opencv-python = "^4.9.0.80"
hydra-core = "^1.3.2"
omegaconf = "^2.3.0"

